---

- name: Build Docker Images on ubuntu server
  hosts: ubuntu
  become: yes
  roles:
    - ubuntu_server

- name: Build Docker Images on CentOS server
  hosts: centos
  become: yes
  roles:
    - centos_server

- name: Run docker container
  hosts: all
  become: yes
  tasks:

    - name: Run Docker Container
      docker_container:
        name: Group3_webapp
        image: web_application
        state: started
        ports:
          - "8080:8080"
