- name: Build Docker Images
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Copy Dockerfile to build server
      copy:
        src: /home/gapisa/Group3_FinalProject/Dockerfile
        dest: /tmp/Dockerfile

    - name: Copy application files to build server
      ansible.builtin.copy:
        src:
          - /home/gapisa/Group3_FinalProject/index.html
          - /home/gapisa/Group3_FinalProject/styles.css
        dest: /tmp/

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: /tmp
        name: my_application
        tag: latest

    - name: Save Docker image to tar file
      ansible.builtin.command:
        cmd: docker save my_application:latest -o /tmp/my_application.tar

    - name: Fetch Docker image tar file
      ansible.builtin.fetch:
        src: /tmp/my_application.tar
        dest: ./docker_images/my_application.tar
        flat: yes
        
- name: Deploy and Run Docker Images
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Copy Docker image tar file to server
      ansible.builtin.copy:
        src: ./docker_images/my_application.tar
        dest: /tmp/my_application.tar

    - name: Load Docker image
      ansible.builtin.command:
        cmd: docker load -i /tmp/my_application.tar

    - name: Run Docker container
      community.docker.docker_container:
        name: my_application_container
        image: my_application:latest
        state: started
        ports:
          - "8080:8080"
  
