- name: Build Docker Images
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present


    - name: Copy Dockerfile to build server
      copy:
        src: /home/gapisa/Group3_FinalProject/Dockerfile
        dest: /home/gapisa/Dockerfile

    - name: Copy index.html file
      copy:
        src: /home/gapisa/Group3_FinalProject/index.html
        dest: /home/gapisa/index.html
        
    - name: Copy styles.css file
      copy:
        src: /home/gapisa/Group3_FinalProject/styles.css
        dest: /home/gapisa/styles.css
                
    - name: Build Docker image
      docker_image:
        name: my_application
        build:
          path: /home/gapisa
        tag: latest

#    - name: Save Docker image to tar file
#      ansible.builtin.command:
#        cmd: docker save my_application:latest -o /tmp/my_application.tar

 #   - name: Fetch Docker image tar file
 #     ansible.builtin.fetch:
 #       src: /tmp/my_application.tar
 #       dest: ./docker_images/my_application.tar
 #       flat: yes
        
- name: Deploy and Run Docker Images
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker.io
        state: present
        
    - name: Start and enable docker services
      service:
        name: docker
        state: started
        enabled: yes

#    - name: Copy Docker image tar file to server
##      ansible.builtin.copy:
#        src: ./docker_images/my_application.tar
#        dest: /tmp/my_application.tar

#    - name: Load Docker image
#      ansible.builtin.command:
#        cmd: docker load -i /tmp/my_application.tar

    - name: Run Docker container
      community.docker.docker_container:
        name: my_application_container
        image: my_application
        state: started
        ports:
          - "8080:8080"
  
