---
- name: Install docker on Ubuntu
  apt:
    name: docker.io
    state: present

- name: Start and Enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy the Dockerfile
  copy:
    src: /home/gapisa/Group3_FinalProject/Dockerfile/
    dest: /home/gapisa/Group3_FinalProject/Dockerfile
    
- name: Copy index file
  copy:
    src: /home/gapisa/Group3_FinalProject/index.html/
    dest: /home/gapisa/Group3_FinalProject/index.html
    
- name: Copy style file
  copy:
    src: /home/gapisa/Group3_FinalProject/styles.css/
    dest: /home/gapisa/Group3_FinalProject/styles.css

- name: Build Docker image
  docker_image:
    name: webapp
    source: build
    build:
      path: /home/gapisa/Group3_FinalProject
    state: present
